# general
batch_size: 512
input_size: 112
embd_shape: 512
sub_name: 'arc_res50'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2'
head_type: ArcHead # 'ArcHead', 'NormHead'
is_ccrop: False # central-cropping or not

# train
train_dataset: './data/faceparsing4.tfrecord'
binary_img: True
num_classes: 1300
num_samples: 64516
epochs: 2000
base_lr: 0.001
w_decay: !!float 5e-4
save_steps: 1000

# test
test_dataset: './data/test_dataset'
